# frontend/pubspec.yaml
name: stepik_clone
description: Кроссплатформенное образовательное приложение (Flutter)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  go_router: ^12.1.1
  dio: ^5.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
