name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  GHCR_PAT: ${{ secrets.GHCR_PAT }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd stepik-clone/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx 'pydantic[email]'
      - name: Run tests
        run: |
          cd stepik-clone/backend
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./stepik-clone/backend
          push: true
          tags: ghcr.io/nurik432/stepik_clone-backend:main

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./stepik-clone/frontend
          push: true
          tags: ghcr.io/nurik432/stepik_clone-frontend:main

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "stepik-clone/docker-compose.prod.yml"
          target: "~/stepik-clone"
          strip_components: 1

      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_PAT
          script: |
            # Авторизуемся для доступа к GitHub Container Registry
            echo "$GHCR_PAT" | docker login ghcr.io -u nurik432 --password-stdin
            
            cd ~/stepik-clone
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d